# Generated by Django 4.2.19 on 2025-03-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("locality", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("openweather", "OpenWeather"),
                            ("netatmo", "Netatmo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("feels_like", models.FloatField(blank=True, null=True)),
                ("humidity", models.IntegerField(blank=True, null=True)),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.weatherstation",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
